version: 1.0.{build}
image: Visual Studio 2017

install:
  - docker version

build_script:
  - git clone -b keneanung-patch-1 https://github.com/keneanung/Mudlet-1.git
  - docker build -t keneanung/mudlet-build-docker-windows .
