version: 1.0.{build}
image: Windows Server 2019

install:
  - docker version

build_script:
  - git clone -b keneanung-patch-1 https://github.com/keneanung/Mudlet-1.git Mudlet
  - docker build -t keneanung/mudlet-build-docker-windows .
