version: 1.0.{build}
image: Visual Studio 2017

environment:
  appveyor_build_worker_cloud: gce

install:
  - docker version

build_script:
  - git clone -b keneanung-patch-1 https://github.com/keneanung/Mudlet-1.git Mudlet
  - docker build -t keneanung/mudlet-build-docker-windows .
